import fs from "node:fs";
import path from "node:path";
import { config } from "@/lib/config";
import * as db from "@/lib/db";
import { publish } from "@/lib/sse";
import { getAgent } from "@/adapters/agents";
import { getValidator } from "@/adapters/validators";
import { validateDeps } from "@/lib/expo-go";
import { gitInit, gitCommit } from "@/lib/git";
import { runCommand } from "@/lib/exec";

/**
 * The generate pipeline: init → agent → qa → ready.
 * Every step is journaled to SQLite + broadcast over SSE, and committed to git,
 * so a disconnected client (or a crash) can resume from the last checkpoint.
 */

const AGENT_CONTEXT = `You are generating an Expo (React Native) app that MUST run in Expo Go.

Hard rules:
- Target the LATEST Expo SDK.
- Use expo-router for navigation and @expo/ui for native UI (sheets, pickers, toggles, menus) — never community libraries like @gorhom/bottom-sheet when @expo/ui provides it.
- Only depend on packages in the Expo Go allow-list (expo-* modules + the official third-party list). If the user asks for something outside it, choose an Expo Go-safe alternative instead.
- Run \`npx tsc --noEmit\` and fix all errors before finishing.
- Never create or edit ios/ or android/ by hand (Continuous Native Generation).`;

type Handler = (type: string, message: string) => void;

export async function runGenerateJob(run: db.Run, project: db.Project): Promise<void> {
  const projectId = project.id;
  const dir = path.join(config.projectsDir, projectId);

  const emit: Handler = (type, message) => {
    db.addEvent({ projectId, runId: run.id, type, message });
    publish({ projectId, runId: run.id, type, message, at: Date.now() });
  };
  const log = (chunk: string) => db.appendRunLog(run.id, chunk);
  const setStatus = (s: db.ProjectStatus) => {
    db.setProjectStatus(projectId, s);
    emit("status", s);
  };

  try {
    // 1. initialize
    setStatus("initializing");
    await initProject(dir, project.agent);
    emit("log", "project initialized");

    // 2. generate
    setStatus("generating");
    const adapter = getAgent(project.agent);
    const env = {
      DEEPSEEK_API_KEY: config.deepseek.apiKey,
      DEEPSEEK_BASE_URL: config.deepseek.baseUrl,
      DEEPSEEK_MODEL: config.deepseek.model,
    };
    let exitCode = 0;
    for await (const ev of adapter.run({
      projectDir: dir,
      prompt: run.input ?? project.prompt,
      context: AGENT_CONTEXT,
      env,
    })) {
      if (ev.type === "output") {
        log(ev.data);
      } else if (ev.type === "error") {
        log(`[stderr] ${ev.data}`);
      } else if (ev.type === "done") {
        exitCode = ev.exitCode;
      }
    }
    if (exitCode !== 0) {
      throw new Error(`agent exited with code ${exitCode}`);
    }

    // 3. qa
    setStatus("qa");
    const qa = await runQa(dir);
    emit("log", `qa: typecheck=${qa.typecheckLog}, expo-go violations=${qa.violations.length}`);

    if (qa.violations.length > 0) {
      setStatus("needs_dev_build");
      emit(
        "error",
        `These dependencies are not in Expo Go and require a development build: ${qa.violations.join(", ")}`
      );
      db.setRunStatus(run.id, "done");
      return;
    }
    if (!qa.typecheckOk) {
      throw new Error("typecheck failed — see run log");
    }

    // 4. commit + ready
    const commit = await gitCommit(dir, "generated by mobile-agent-studio");
    db.setRunCommit(run.id, commit ?? "no-change");

    // 5. optional validator (V1 = none / human)
    const validator = getValidator(config.defaultValidator);
    const vres = await validator.validate(dir);
    if (!vres.ok) {
      throw new Error(`validator failed: ${vres.details.join("; ")}`);
    }

    setStatus("ready");
    emit("ready", "App is ready — review it in Expo Go, then tap Launch");
    db.setRunStatus(run.id, "done");
  } catch (err) {
    db.setRunError(run.id, err instanceof Error ? err.message : String(err));
    db.setProjectStatus(projectId, "failed");
    emit("error", err instanceof Error ? err.message : String(err));
    db.setRunStatus(run.id, "failed");
  }
}

async function initProject(dir: string, agent: string): Promise<void> {
  fs.mkdirSync(dir, { recursive: true });

  // dry-run writes its own minimal project; real agents need a scaffold.
  if (agent !== "dry-run" && !fs.existsSync(path.join(dir, "package.json"))) {
    const r = await runCommand(
      "npx",
      ["create-expo-app@latest", ".", "--template", "default", "--yes"],
      { cwd: dir, timeoutMs: 300_000 }
    );
    if (r.code !== 0) {
      throw new Error(`create-expo-app failed: ${r.stderr.slice(-500)}`);
    }
  }

  if (!fs.existsSync(path.join(dir, ".git"))) {
    await gitInit(dir);
  }
}

async function runQa(dir: string): Promise<{
  violations: string[];
  typecheckOk: boolean;
  typecheckLog: string;
}> {
  let violations: string[] = [];
  const pkgPath = path.join(dir, "package.json");
  if (fs.existsSync(pkgPath)) {
    const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
    violations = validateDeps(pkg).violations;
  }

  let typecheckOk = true;
  let typecheckLog = "skipped (no tsconfig)";
  if (fs.existsSync(path.join(dir, "tsconfig.json"))) {
    const r = await runCommand("npx", ["tsc", "--noEmit"], { cwd: dir, timeoutMs: 120_000 });
    typecheckOk = r.code === 0;
    typecheckLog = typecheckOk ? "ok" : "failed";
  }

  return { violations, typecheckOk, typecheckLog };
}
